
import "./globals.css";

import Providers from "@/components/theme-provider";

import "@/styles/toast.css";
import AppToaster from "@/components/theme-toaster";


export const metadata = {
  title: "To Do",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-scroll-behavior="smooth" suppressHydrationWarning>
      <body suppressHydrationWarning>
        <Providers>
          {children}
          <AppToaster />
        </Providers>
      </body>
    </html>
  );
}
